stages:
  - build

image: docker:19.03
variables:
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03-dind

build:
  stage: build
  script:
    - export UPSTREAM_COMMIT=$(git log --invert-grep --author="ted.tramonte@gmail.com" -n 1 --pretty=format:'%h')
    - docker build -t tedtramonte/steamwebpipes:${UPSTREAM_COMMIT} ./
    - docker tag tedtramonte/steamwebpipes:${UPSTREAM_COMMIT} ${CI_REGISTRY_IMAGE}:${UPSTREAM_COMMIT}
    - docker tag tedtramonte/steamwebpipes:${UPSTREAM_COMMIT} tedtramonte/steamwebpipes:latest
    - docker tag tedtramonte/steamwebpipes:${UPSTREAM_COMMIT} ${CI_REGISTRY_IMAGE}:latest

    # Docker Hub
    - docker login -u tedtramonte -p $DOCKER_HUB_TOKEN
    - docker push tedtramonte/steamwebpipes:${UPSTREAM_COMMIT}
    - docker push tedtramonte/steamwebpipes:latest

    # GitLab Registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}:${UPSTREAM_COMMIT}
    - docker push ${CI_REGISTRY_IMAGE}:latest
